// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // ✅ Return the correct FirebaseOptions for web
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyASmeAPfpXkYDA3FYB3C9rPnvPgyoPqmHo",
    authDomain: "sample-firebase-ai-app-3c7c7.firebaseapp.com",
    projectId: "sample-firebase-ai-app-3c7c7",
    storageBucket: "sample-firebase-ai-app-3c7c7.firebasestorage.app",
    messagingSenderId: "1081967173605",
    appId: "1:1081967173605:web:2dacb1a3ae24f60d41590c",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfX2oIyVkbbkMRZUFiLuDo2N-RSH6w0LI',
    appId: '1:131108270717:android:b57cc73cfc333ef09df714',
    messagingSenderId: '131108270717',
    projectId: 'recipe-f52a8',
    storageBucket: 'recipe-f52a8.firebasestorage.app',
  );
}
